name: Node Tests

on:
  push:
    branches: ["main", "develop", "feature/**"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout specs
        uses: actions/checkout@v4
        with:
          repository: lcod-team/lcod-spec
          path: lcod-spec
      - name: Checkout resolver
        uses: actions/checkout@v4
        with:
          repository: lcod-team/lcod-resolver
          path: lcod-resolver
      - name: Checkout components
        uses: actions/checkout@v4
        with:
          repository: lcod-team/lcod-components
          path: lcod-components
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        env:
          SPEC_REPO_PATH: ${{ github.workspace }}/lcod-spec
          LCOD_RESOLVER_PATH: ${{ github.workspace }}/lcod-resolver
          LCOD_RESOLVER_COMPONENTS_PATH: ${{ github.workspace }}/lcod-resolver/packages/resolver/components
          LCOD_COMPONENTS_PATH: ${{ github.workspace }}/lcod-components
        run: npm test
      - name: Run spec fixtures
        env:
          SPEC_REPO_PATH: ${{ github.workspace }}/lcod-spec
          LCOD_COMPONENTS_PATH: ${{ github.workspace }}/lcod-components
        run: npm run test:spec
